### ISSUE TITLE
Cron

### ISSUE THREAD

**Issue by ItHasU** [ItHasU/MQTTToolbox#11]
It would be useful to plan some actions/messages that would be schedules as a cron job. This would allow to schedule repetitive actions for some devices (heaters, lamps, ...)

# Tasks

- [x] Allow to add a new planned message
- [x] Group planned messages by scenario
- [x] Name scenario
- [x] Allow to enable / disable scenarios
- [x] Plan next message to be sent from current date & scenarios (+ unit test)
